In [1]:
import numpy as np
import pandas as pd
import time


In [2]:
np.random.seed(42)

students = 1000

math_scores = np.random.randint(40, 100, students)
science_scores = np.random.randint(35, 100, students)
english_scores = np.random.randint(45, 100, students)
attendance = np.random.randint(60, 100, students)

dataset = np.column_stack((math_scores, science_scores, english_scores, attendance))

print("Dataset Shape:", dataset.shape)
print("\nFirst 5 rows:\n", dataset[:5])


Dataset Shape: (1000, 4)

First 5 rows:
 [[78 68 87 64]
 [91 73 92 70]
 [68 60 67 71]
 [54 68 50 69]
 [82 88 90 67]]


In [3]:
# Access first student record
print("First Student Record:", dataset[0])

# Access Math scores (first column)
math_column = dataset[:, 0]
print("First 10 Math Scores:", math_column[:10])

# Slice first 5 students
print("First 5 Students:\n", dataset[:5])

# Students with index 100 to 110
print("Students 100-110:\n", dataset[100:111])


First Student Record: [78 68 87 64]
First 10 Math Scores: [78 91 68 54 82 47 60 78 97 58]
First 5 Students:
 [[78 68 87 64]
 [91 73 92 70]
 [68 60 67 71]
 [54 68 50 69]
 [82 88 90 67]]
Students 100-110:
 [[53 51 80 79]
 [62 47 83 75]
 [99 59 54 93]
 [96 44 69 61]
 [79 52 62 94]
 [60 68 63 99]
 [55 42 80 87]
 [84 74 54 98]
 [57 76 77 65]
 [86 75 99 68]
 [92 40 94 79]]


In [4]:
# Add 5 bonus marks to all subjects (except attendance)
bonus_dataset = dataset.copy()
bonus_dataset[:, :3] += 5

print("After Adding Bonus:\n", bonus_dataset[:5])


After Adding Bonus:
 [[83 73 92 64]
 [96 78 97 70]
 [73 65 72 71]
 [59 73 55 69]
 [87 93 95 67]]


In [5]:
# Average score per student
avg_per_student = np.mean(dataset[:, :3], axis=1)

# Average score per subject
avg_per_subject = np.mean(dataset[:, :3], axis=0)

print("Average per Student (first 5):", avg_per_student[:5])
print("Average per Subject (Math, Science, English):", avg_per_subject)


Average per Student (first 5): [77.66666667 85.33333333 65.         57.33333333 86.66666667]
Average per Subject (Math, Science, English): [70.2   66.672 71.825]


In [6]:
print("Mean:", np.mean(dataset[:, :3]))
print("Median:", np.median(dataset[:, :3]))
print("Standard Deviation:", np.std(dataset[:, :3]))
print("Maximum Score:", np.max(dataset[:, :3]))
print("Minimum Score:", np.min(dataset[:, :3]))


Mean: 69.56566666666667
Median: 69.5
Standard Deviation: 17.471529828711496
Maximum Score: 99
Minimum Score: 35


In [7]:
reshaped = dataset[:, :3].reshape(1000, 3)
print("Reshaped Shape:", reshaped.shape)


Reshaped Shape: (1000, 3)


In [8]:
np.save("student_scores.npy", dataset)


In [9]:
loaded_data = np.load("student_scores.npy")
print("Loaded Data Shape:", loaded_data.shape)


Loaded Data Shape: (1000, 4)
